spring:
  mail:
    host: smtp.qq.com
    username: 972193026@qq.com
    password: efqlzlrhujbsbdbi
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8