spring:
  redis:
    database: 0
    host: 117.50.65.187
    port: 6379
    jedis:
      pool:
        # 连接池最大限制
        max-active: 9
        # 连接池最大阻塞时间(负值表示没有限制)
        max-wait: -1
        # 连接池中最多的空闲连接
        max-idle: 8
        # 连接池中最少的空闲连接
        min-idle: 0
server:
  port: 8080